language: python
python:
  - 2.7
cache:
  directories:
   - eggs
   - $HOME/.local
install:
  - deactivate
  - pip install --user psycopg2
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
