language: python
sudo: false
python:
  - 3.5
# addons:
#   apt:
#     packages:
#     - python3-psycopg2
cache:
  directories:
    - eggs
    - $HOME/.local
install:
  - pip install psycopg2
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/test
after_success:
  - bin/coveralls
