language: python
sudo: false
python:
  - "3.5"
install:
  - docker-compose build
  - docker-compose run web buildout
script:
  - docker-compose run web bin/test
after_success:
  - docker-compose run web bin/coveralls
