language: python
sudo: false
python:
  - 3.5
services:
  - postgres
cache:
  directories:
    - eggs
    - $HOME/.local
install:
  - psql -c 'create user buildout with superuser password buildout;' -U postgres
  - pip install psycopg2
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/test
after_success:
  - bin/coveralls
