language: python
sudo: false
python:
  - "3.5"
services:
  - postgres
cache:
  directories:
    - eggs
    - $HOME/.local
install:
  - psql -c "create user buildout with password 'buildout' superuser;" -U postgres
  - pip install -U psycopg2 zc.buildout setuptools
  - buildout -v
script:
  - bin/test
after_success:
  - bin/coveralls
