language: python
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
     - python-psycopg2
cache:
  directories:
   - eggs
   - $HOME/.local
install:
  - deactivate
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/test
after_success:
  - bin/coveralls
