language: python
sudo: false
python:
  - 3.5
cache:
  directories:
   - eggs
   - $HOME/.local
install:
  - pip install python3-psycopg2
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/test
after_success:
  - bin/coveralls
