language: python
sudo: false
python:
  - 3.5
cache:
  directories:
   - eggs
   - $HOME/.local
install:
  - python bootstrap.py
  - bin/buildout -v
script:
  - bin/coverage run bin/test
  - bin/coverage report
  - bin/coverage xml
after_success:
  - bin/coveralls
