# Follows this structure (loosely): https://docs.docker.com/compose/django/
#
# Setup databases, and run buildout once again:
#   $ docker-compose run web ./docker-bootstrap.sh
#
# Start your services:
#   $ docker-compose up (-d)

version: '2'
services:
  web:
    build: .
    command: bin/django runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - .:/buildout

# Note: command is the default when you run "up".  We don't want it in the
# dockerfile as you'd have to do the full setup there, otherwise.


# $ docker-compose run web buildout