version: '2'
services:

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 'buildout'
      POSTGRES_USER: 'buildout'
      POSTGRES_DB: 'sso'
      PGDATA: '/var/lib/postgresql/data/pgdata'

  web:
    build: .
    command: "bin/python manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/code:delegated
    # Switch on PYTHONWARNINGS when you want to see deprecation warnings.
    environment:
      PYTHONWARNINGS: "default"
    depends_on:
      - db

volumes:
  pgdata:
